### ISSUE TITLE
[ERROR - 23:48:30] 自动启动API服务失败，找不到`node/app.js`，请手动启动。

### ISSUE THREAD

**Issue by zzZeroOne** [cwuom/MusicHelper#1]
[ERROR - 23:48:30] 自动启动API服务失败，找不到`node/app.js`，请手动启动。
你好windows11使用exe版本遇到这个问题。

**Comment by cwuom** [comment]
https://github.com/cwuom/MusicHelper#%E9%99%84%E5%8A%A0%E7%BB%84%E4%BB%B6%E4%B8%8B%E8%BD%BD%EF%B8%8F
